services:
  dataservice:
    build: ./dataservice
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  orderservice:
    build: ./graphql
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  
  authservice:
    build: ./auth
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  
  productservice:
    build: ./product
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  
  userservice:
    build: ./users
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
