server:
  port: 8082

stripe:
  secretKey: sk_test_51JlxjKIsIcjwovka9A1bd98rPcNPhsPb5EigmVUCRkvopovGq6fDTfYKhFfADyX2x0cPA3PYkIYqDUR11qzWOjr800QNTgN27m # Replace with your actual Stripe Secret Key

logging:
  level:
    root: INFO
    com.graphql: DEBUG
    main.java.com.graphql.util: DEBUG
