spring:
  cloud:
    gateway:
      globalcors:  # Global CORS configuration
        corsConfigurations:
          '[/**]': 
            allowedOrigins: "http://localhost:3000"  # Allow frontend requests
            allowedMethods:  # Allowed HTTP methods
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"  # Allow all headers
            allowCredentials: true  # Allow credentials
  data:
    mongodb:
      uri: mongodb+srv://doapps-8228c598-bbfb-49e7-9a0f-5552620ad085:2658kXKF7GtD309M@db-mongodb-fra1-68366-638f76d0.mongo.ondigitalocean.com/kronen?tls=true&authSource=admin&replicaSet=db-mongodb-fra1-68366

