spring:
  cloud:
    gateway:
      globalcors:  # Global CORS configuration
        corsConfigurations:
          '[/**]': 
            allowedOrigins: "http://localhost:3000"  # Allow frontend requests
            allowedMethods:  # Allowed HTTP methods
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"  # Allow all headers
            allowCredentials: true  # Allow credentials